// Blur placeholders for next/image — generated by `npm run blur`
// (scripts/generate-blur.mjs). Import from SERVER components only; the map
// is ~200KB and must not land in a client bundle. Client components receive
// individual data URLs as props.

import blurMap from "@/data/blur-map.json";

const map = blurMap as Record<string, string>;

export function getBlur(src: string): string | undefined {
  return map[src];
}

/** Props spread for next/image: blur when we have one, plain otherwise. */
export function blurProps(src: string):
  | { placeholder: "blur"; blurDataURL: string }
  | Record<string, never> {
  const blurDataURL = map[src];
  return blurDataURL ? { placeholder: "blur", blurDataURL } : {};
}
